[future-incompat-report]
frequency = "always"

[build]
rustflags = [
  "--cfg",
  "tokio_unstable",
  # "-Clink-arg=-fuse-ld=mold",
  "-Ctarget-cpu=native",
  # "-Zshare-generics=y",
  # "-Clink-arg=-Wl,--no-rosegment",
]

# [target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
