#    This file is part of Eruption.
#
#    Eruption is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Eruption is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Eruption.  If not, see <http://www.gnu.org/licenses/>.
#
#    Copyright (c) 2019-2022, The Eruption Development Team


[package]
name = "eruption"
version = "0.1.24"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2021"
description = "Eruption Linux user-mode input and LED driver for keyboards, mice and other devices"
repository = "https://github.com/X3n0m0rph59/eruption.git"
license = "GPLv3+"
readme = "README.md"
resolver = "2"

[features]
default = [] #["mimalloc_allocator"]
mimalloc_allocator = ["mimalloc"]

[dependencies]
mimalloc = { version = "0.1.28", optional = true, default-features = false }
cfg-if = "1.0.0"
crossbeam = "0.8.1"
futures = "0.3.21"
parking_lot = { version = "0.12.0", features = ["deadlock_detection"] }
async-trait = "0.1.53"
#tracing = "0.1.26"
#tracing-futures = "0.2.5"
#tracing-subscriber = "0.2.20"
libc = "0.2.121"
nix = "0.23.1"
log = "0.4.16"
syslog = "6.0.1"
pretty_env_logger = "0.4.0"
thiserror = "1.0.30"
eyre = "0.6.7"
color-eyre = "0.6.1"
toml = "0.5.8"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full", "rt-multi-thread"] }
socket2 = { version = "0.4.4", features = ["all"] }
ctrlc = { version = "3.2.1", features = ["termination"] }
clap = "3.1.6"
hotwatch = "0.4.6"
config = "0.12.0"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.6.3"
evdev-rs = "0.5.0"
hexdump = "0.1.1"
byteorder = "1.4.3"
itertools = "0.10.3"
rayon = "1.5.1"
lazy_static = "1.4.0"
rand = "0.8.5"
csscolorparser = "0.5.0"
colorgrad = "0.5.0"
palette = "0.6.0"
nalgebra = "0.30.1"
noise = "0.7.0"
simdnoise = "3.1.6"
#lua-src = "544.0.0"
#mlua = { version = "0.7.3", features = ["lua54", "vendored"] }
#luajit-src = "210.3.2+resty1085a4d"
#mlua = { version = "0.7.3", features = ["luajit52"] }
mlua = { version = "0.7.4", features = ["lua54"] }
sysinfo = "0.23.5"
procinfo = "0.4.2"
bincode = "2.0.0-rc.1"
rustfft = "6.0.1"
uuid = { version = "1.0.0-alpha.1", features = ["serde", "v4"] }
dbus = "0.9.5"
dbus-tree = "0.9.2"
paste = "1.0.6"
bitvec = "1.0.0"
serialport = "4.0.1"
crc8 = "0.1.1"
bytes = "1.1.0"
prost = "0.9.0"
prost-types = "0.9.0"
i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"] }
rust-embed = "6.3.0"
unic-langid = "0.9.0"
icecream = "0.1.0"

# ubuntu bionic
# sysinfo = "=0.14.2"

[dev-dependencies]
pretty_assertions = "1.2.0"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["test-util"] }

[build-dependencies]
prost-build = "0.9.0"
