#  SPDX-License-Identifier: GPL-3.0-or-later
#
#  This file is part of Eruption.
#
#  Eruption is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Eruption is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Eruption.  If not, see <http://www.gnu.org/licenses/>.
#
#  Copyright (c) 2019-2023, The Eruption Development Team

[package]
name = "eruption"
version = "0.4.0"
build = "build.rs"
authors = [
  "X3n0m0rph59 <x3n0m0rph59@gmail.com>",
  "The Eruption Development Team",
]
edition = "2021"
rust-version = "1.65"
description = "Realtime RGB LED Driver for Linux"
repository = "https://github.com/X3n0m0rph59/eruption.git"
homepage = "https://eruption-project.org"
keywords = ["eruption", "linux", "led", "driver"]
categories = ["hardware-support"]
license = "GPL-3.0-or-later"
readme = "README.md"
resolver = "2"

[features]
default = []                      #["mimalloc_allocator"]
mimalloc_allocator = ["mimalloc"]
profiling = ["coz"]
debug-async = []

[dependencies]
mimalloc = { version = "0.1.38", optional = true, default-features = false }
coz = { version = "0.1.3", optional = true }
cfg-if = "1.0.0"
flume = { version = "0.11.0", features = ["async"] }
parking_lot = { version = "0.12.1", features = ["deadlock_detection"] }
async-trait = "0.1.73"
tracing = "0.1.37"
tracing-journald = "0.3.0"
tracing-futures = "0.2.5"
tracing-log = { version = "0.1.3", features = ["env_logger"] }
tracing-subscriber = { version = "0.3.17", features = [
  "parking_lot",
  "registry",
  "env-filter",
] }
console-subscriber = { version = "0.1.10", features = ["parking_lot"] }
libc = "0.2.147"
nix = { version = "0.27.1", features = ["process", "user", "fs", "poll"] }
is-terminal = "0.4.9"
syslog = "6.1.0"
thiserror = "1.0.47"
eyre = "0.6.8"
color-eyre = "0.6.2"
toml = "0.7.6"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full", "tracing", "test-util"] }
socket2 = { version = "0.5.3", features = ["all"] }
ctrlc = { version = "3.4.0", features = ["termination"] }
clap = "4.3.24"
hotwatch = "0.5.0"
config = "0.13.3"
hidapi = { git = "https://github.com/X3n0m0rph59/hidapi-rs.git", rev = "a842fd6", default-features = false, features = [
  "linux-native",
] }
udev = "0.7"
evdev-rs = "0.6.1"
hexdump = "0.1.1"
byteorder = "1.4.3"
indexmap = { version = "2.0.0", features = ["serde"] }
itertools = "0.11.0"
rayon = "1.7.0"
lazy_static = "1.4.0"
rand = "0.8.5"
colorgrad = "0.6.2"
csscolorparser = { version = "0.6.2", features = ["serde"] }
palette = "0.7.3"
nalgebra = "0.32.3"
noise = "0.8.2"
simdnoise = "3.1.6"
# lua-src = "544.0.1"
luajit-src = "210.4.8"
mlua = { version = "0.9.1", features = ["luajit52", "vendored"] }
sysinfo = "0.29.9"
bincode = "2.0.0-rc.3"
rustfft = "6.1.0"
uuid = { version = "1.4.1", features = ["serde", "v4"] }
dbus = "0.9.7"
dbus-tree = "0.9.2"
paste = "1.0.14"
bitvec = "1.0.1"
serialport = "4.2.2"
crc8 = "0.1.1"
crc16 = "0.4.0"
bytes = "1.4.0"
prost = "0.12.0"
prost-types = "0.12.0"
i18n-embed = { version = "0.13.9", features = [
  "fluent-system",
  "desktop-requester",
] }
rust-embed = { version = "6.8.1", features = ["compression"] }
unic-langid = "0.9.1"
icecream = "0.1.0"
same-file = "1"
systemd = "0.10.0"
bitfield-struct = "0.5.4"
transpose = "0.2.2"

# ubuntu bionic
# sysinfo = "=0.14.2"

[dev-dependencies]
pretty_assertions = "1.4.0"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full", "tracing", "test-util"] }

[build-dependencies]
build-data = "0.1"
prost-build = "0.12.0"
